apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o samvaad-k8s/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: https-proxy
  name: https-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: https-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o samvaad-k8s/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: https-proxy
    spec:
      containers:
        - env:
            - name: ALLOWED_DOMAINS
          image: valian/docker-nginx-auto-ssl
          name: https_proxy
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/fullchain.pem
              name: https-proxy-claim0
            - mountPath: /etc/nginx/conf.d/privkey.pem
              name: https-proxy-claim1
            - mountPath: /etc/nginx/conf.d/bbb-docker.conf
              name: https-proxy-claim2
      restartPolicy: Always
      volumes:
        - name: https-proxy-claim0
          persistentVolumeClaim:
            claimName: https-proxy-claim0
        - name: https-proxy-claim1
          persistentVolumeClaim:
            claimName: https-proxy-claim1
        - name: https-proxy-claim2
          persistentVolumeClaim:
            claimName: https-proxy-claim2
status: {}
